source 'https://rubygems.org'

#ruby "~> 2.0"
gem 'mail'
gem 'sqlite3'
gem 'activerecord', require: 'active_record'

gem 'watir-webdriver'
gem 'headless'
gem 'nokogiri'
gem 'pry'
gem 'net'
gem 'dotenv'

